#!/bin/bash
echo "<!-- AUTOGENERATED FILE DO NOT EDIT -->" > README.md
echo "" >> README.md
echo "# XION Mainnet Contracts" >> README.md
echo "" >> README.md
echo "Contract information for XION mainnet" >> README.md
echo "" >> README.md


echo "## Development" >> README.md
echo "" >> README.md
echo "### Compiling" >> README.md
echo "" >> README.md
echo "\`\`\`bash" >> README.md
echo "" >> README.md
echo "docker run --rm -v \"\$(pwd)\":/code \\" >> README.md
echo "  --mount type=volume,source=\"\$(basename \"\$(pwd)\")_cache\",target=/target \\" >> README.md
echo "  --mount type=volume,source=registry_cache,target=/usr/local/cargo/registry \\" >> README.md
echo "  cosmwasm/optimizer:0.16.1" >> README.md
echo "" >> README.md
echo "\`\`\`" >> README.md
echo "" >> README.md


echo "## Deployed Contracts" >> README.md
echo "| Name | Description | Release | Author | Code ID | Hash | Governance Proposal |" >> README.md
echo "|:-----|:------------|:--------|:-------|:--------|:-----|:-------------------|" >> README.md

jq -r '.[] | select(.deprecated != true) | "| \(.name) | \(.description // "") | \(if .release then "[\(.release.version)](\(.release.url))" else "" end) | \(if .author then "[\(.author.name)](\(.author.url))" else "" end) | `\(.code_id // "")` | `\(.hash)` | \(.governance // "") |"' contracts.json >> README.md


echo "## Deprecated Contracts" >> README.md
echo "| Name | Description | Release | Author | Code ID | Hash | Governance Proposal |" >> README.md
echo "|:-----|:------------|:--------|:-------|:--------|:-----|:-------------------|" >> README.md
jq -r '.[] | select(.deprecated == true) | "| \(.name) | \(.description // "") | \(if .release then "[\(.release.version)](\(.release.url))" else "" end) | \(if .author then "[\(.author.name)](\(.author.url))" else "" end) | `\(.code_id // "")` | `\(.hash)` | \(.governance // "") |"' contracts.json >> README.md
