#!/bin/bash
echo "<!-- AUTOGENERATED FILE DO NOT EDIT -->" > contracts.md
echo "" >> contracts.md
echo "# XION Mainnet Contracts" >> contracts.md
echo "" >> contracts.md
echo "Contract information for XION mainnet" >> contracts.md
echo "" >> contracts.md
echo "## Development" >> contracts.md
echo "" >> contracts.md
echo "### Compiling" >> contracts.md
echo "" >> contracts.md
echo "\`\`\`bash" >> contracts.md
echo "" >> contracts.md
echo "docker run --rm -v \"\$(pwd)\":/code \\" >> contracts.md
echo "  --mount type=volume,source=\"\$(basename \"\$(pwd)\")_cache\",target=/target \\" >> contracts.md
echo "  --mount type=volume,source=registry_cache,target=/usr/local/cargo/registry \\" >> contracts.md
echo "  cosmwasm/optimizer:0.16.1" >> contracts.md
echo "" >> contracts.md
echo "\`\`\`" >> contracts.md
echo "" >> contracts.md
echo "## Deployed Contracts" >> contracts.md
echo "| Name | Description | Release | Author | Code ID | Hash | Governance Proposal |" >> contracts.md
echo "|:-----|:------------|:--------|:-------|:--------|:-----|:-------------------|" >> contracts.md

jq -r '.[] | select(.deprecated != true) | "| \(.name) | \(.description // "") | \(if .release then "[\(.release.version)](\(.release.url))" else "" end) | \(if .author then "[\(.author.name)](\(.author.url))" else "" end) | `\(.code_id // "")` | `\(.hash)` | \(.governance // "") |"' contracts.json >> contracts.md


echo "## Deprecated Contracts" >> contracts.md
echo "| Name | Description | Release | Author | Code ID | Hash | Governance Proposal |" >> contracts.md
echo "|:-----|:------------|:--------|:-------|:--------|:-----|:-------------------|" >> contracts.md
jq -r '.[] | select(.deprecated == true) | "| \(.name) | \(.description // "") | \(if .release then "[\(.release.version)](\(.release.url))" else "" end) | \(if .author then "[\(.author.name)](\(.author.url))" else "" end) | `\(.code_id // "")` | `\(.hash)` | \(.governance // "") |"' contracts.json >> contracts.md
